// Cards
export const CARD_MASTER_FLEET_SIMS_FLEETS_MTN = 0;
export const CARD_MASTER_FLEET_SIMS_FLEETS_YUP = 1;
export const CARD_MASTER_FLEET_SIMS_FLEETS_ORANGE = 2;
export const CARD_FLEET_FLEET_SIMS_FLEETS_MTN = 3;
export const CARD_FLEET_FLEET_SIMS_FLEETS_YUP = 4;
export const CARD_FLEET_FLEET_SIMS_FLEETS_ORANGE = 5;
export const CARD_COLLECTOR_FLEET_SIMS_FLEETS_MTN = 6;
export const CARD_COLLECTOR_FLEET_SIMS_FLEETS_YUP = 7;
export const CARD_COLLECTOR_FLEET_SIMS_FLEETS_ORANGE = 8;

// Labels
export const LABEL_MASTER_FLEET_SIMS_FLEETS_YUP = "SOLDE FLOTTE MASTER YUP";
export const LABEL_MASTER_FLEET_SIMS_FLEETS_MTN = "SOLDE FLOTTE MASTER MTN";
export const LABEL_MASTER_FLEET_SIMS_FLEETS_ORANGE = "SOLDE FLOTTE MASTER ORANGE";
export const LABEL_FLEET_FLEET_SIMS_FLEETS_YUP = "SOLDE FLOTTE FLOTTAGE YUP";
export const LABEL_FLEET_FLEET_SIMS_FLEETS_MTN = "SOLDE FLOTTE FLOTTAGE MTN";
export const LABEL_FLEET_FLEET_SIMS_FLEETS_ORANGE = "SOLDE FLOTTE FLOTTAGE ORANGE";
export const LABEL_COLLECTOR_FLEET_SIMS_FLEETS_YUP = "SOLDE FLOTTE RESPONSABLE YUP";
export const LABEL_COLLECTOR_FLEET_SIMS_FLEETS_MTN = "SOLDE FLOTTE RESPONSABLE MTN";
export const LABEL_COLLECTOR_FLEET_SIMS_FLEETS_ORANGE = "SOLDE FLOTTE RESPONSABLE ORANGE";